### ISSUE TITLE
Are there plans to support inline chunks?

### ISSUE THREAD

**Issue by 7enderhead** [entangled/entangled#108]
As far as I have found out (is there explicit documentation about this?) it seems that chunks have to appear on their own lines to be substituted by their definitions:

````
```{.whatever #bar}
here comes bar's code
```

foo
// substitution works
<<bar>>
baz

// no substitution
foo <<bar>> baz
````

Are there any plans to support 'inline chunks', which would be helpful to document complicated expressions without having to resort to weird newline formatting in the target programming language (if that's even possible) or defining 'helper functions/methods', which might impact performance?

**Comment by jhidding** [comment]
currently no. There are a few languages out there where angle brackets are legal syntax. Second, inline references would have different rules for expanding newlines. The stitching mechanism works by scanning entire lines of comment for code block meta data, so that also would have to change. Currently this would add quite a bit of complexity to the system. I don't have the time to implement this myself.
