### ISSUE TITLE
Support output languages without comments

### ISSUE THREAD

**Issue by mgajda** [entangled/entangled#27]
JSON does not allow comments, and it can be used for configuration or test example.
It would be nice to allow a language that does not have any comments at all.

An alternative way of handling this would be to allow to define per-language postprocessor.

**Comment by jhidding** [comment]
This is a nice idea, but it will not trivial to implement. We would have to introduce target files that are not listened to, and the user has to understand this. Once we have version 1.0 out, we can think about including this.

**Comment by jhidding** [comment]
I will not implement this any hime soon. If you have a proposal how to make this work  I'm glad to hear it.

**Comment by MasterOfTheTiger** [comment]
How about a Markdown class like `one-way` or something? For example, `{.json .one-way file=config.json}`?

**Comment by jhidding** [comment]
That is one way to indicate that a file should be treated differently. The real problem is that these files need to be treated differently throughout the program:
- The database would gain another entry in the `targets` table
- The tangle code should be made aware
- `listTargetFiles` should not list the `one-way` targets for the daemon, but if the user runs `entangled list` these files should be included?

Implementing this would take quite some time and the pay-off is minor. I know of only one "language" that is in broad use that doesn't (formally) support comments and its JSON. If you really need JSON, you could write the output to an alternate location and use a rule in a Makefile to strip the comments.

**Comment by mgajda** [comment]
A more careful look indicates that there is unofficial standard of adding ["_comment" key](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json) to the object, but this cannot be placed arbitrarily in the input.

**Comment by jhidding** [comment]
Just for JSON I think it would be easier to add a post-processing step; removing all lines starting with `#` for instance. This would be very easy to configure once the Milkshake update is out.
